[project]
name = "de_quoi_parle_le_monde"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jherve", email = "julien.jev.herve@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
